import type { NextPage } from 'next';
import Image from 'next/image';
import Head from 'next/head';

import Footer from '@components/footer/Footer';
import Intro from '@components/intro/Intro';
import Projects from '@components/projects/Projects';
import Skills from '@components/skills/Skills';
import Header from '@components/header/Header';

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
				/>
			</Head>
			<Header />
			<main>
				<Intro />
				<Skills />
				<Projects />
			</main>
			<Footer />
		</>
	);
};

export default Home;
